// <auto-generated />
using System;
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEnd.Migrations
{
    [DbContext(typeof(AmruDbContext))]
    [Migration("20191024130850_BigSeed")]
    partial class BigSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BackEnd.Models.PhoneNumber", b =>
                {
                    b.Property<int>("PhoneNumberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PhoneNumberID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("PhoneNumbers");

                    b.HasData(
                        new
                        {
                            PhoneNumberID = 1,
                            Number = "(933) 548-2349",
                            UserID = 1
                        },
                        new
                        {
                            PhoneNumberID = 2,
                            Number = "(920) 558-2158",
                            UserID = 2
                        },
                        new
                        {
                            PhoneNumberID = 3,
                            Number = "(816) 448-2524",
                            UserID = 3
                        },
                        new
                        {
                            PhoneNumberID = 4,
                            Number = "(866) 517-3903",
                            UserID = 4
                        },
                        new
                        {
                            PhoneNumberID = 5,
                            Number = "(892) 539-2626",
                            UserID = 5
                        },
                        new
                        {
                            PhoneNumberID = 6,
                            Number = "(975) 562-3728",
                            UserID = 6
                        },
                        new
                        {
                            PhoneNumberID = 7,
                            Number = "(951) 538-2988",
                            UserID = 7
                        },
                        new
                        {
                            PhoneNumberID = 8,
                            Number = "(861) 568-2968",
                            UserID = 8
                        },
                        new
                        {
                            PhoneNumberID = 9,
                            Number = "(832) 409-3078",
                            UserID = 9
                        });
                });

            modelBuilder.Entity("BackEnd.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("PaymentEmail")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "reillyholden@jamnation.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "cillum",
                            Password = "amet",
                            PaymentEmail = "reillyholden@jamnation.com",
                            Username = "cupidatat"
                        },
                        new
                        {
                            UserID = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "reillyholden@jamnation.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "labore",
                            Password = "et",
                            PaymentEmail = "reillyholden@jamnation.com",
                            Username = "labore"
                        },
                        new
                        {
                            UserID = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "reillyholden@jamnation.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ut",
                            Password = "aliqua",
                            PaymentEmail = "reillyholden@jamnation.com",
                            Username = "dolore"
                        },
                        new
                        {
                            UserID = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "reillyholden@jamnation.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "dolor",
                            Password = "in",
                            PaymentEmail = "reillyholden@jamnation.com",
                            Username = "veniam"
                        },
                        new
                        {
                            UserID = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "reillyholden@jamnation.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "esse",
                            Password = "mollit",
                            PaymentEmail = "reillyholden@jamnation.com",
                            Username = "consectetur"
                        },
                        new
                        {
                            UserID = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "reillyholden@jamnation.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "consectetur",
                            Password = "voluptate",
                            PaymentEmail = "reillyholden@jamnation.com",
                            Username = "consequat"
                        },
                        new
                        {
                            UserID = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "reillyholden@jamnation.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "pariatur",
                            Password = "ut",
                            PaymentEmail = "reillyholden@jamnation.com",
                            Username = "officia"
                        },
                        new
                        {
                            UserID = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "reillyholden@jamnation.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "irure",
                            Password = "in",
                            PaymentEmail = "reillyholden@jamnation.com",
                            Username = "nostrud"
                        },
                        new
                        {
                            UserID = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "reillyholden@jamnation.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "laborum",
                            Password = "cillum",
                            PaymentEmail = "reillyholden@jamnation.com",
                            Username = "anim"
                        });
                });

            modelBuilder.Entity("BackEnd.Models.PhoneNumber", b =>
                {
                    b.HasOne("BackEnd.Models.User", "User")
                        .WithOne("PhoneNumber")
                        .HasForeignKey("BackEnd.Models.PhoneNumber", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
