// <auto-generated />
using System;
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEnd.Migrations
{
    [DbContext(typeof(AmruDbContext))]
    [Migration("20191027192447_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BackEnd.Models.Address", b =>
                {
                    b.Property<uint>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("GarageID")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<string>("LineOne")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("LineTwo")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("AddressID");

                    b.HasIndex("GarageID")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressID = 1u,
                            County = "Greater Manchester",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 1u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 53.499447799999999,
                            LineOne = "Quantum Park",
                            LineTwo = "Monsall Rd",
                            Longitude = -2.2026933,
                            PostCode = "M40 8FY"
                        },
                        new
                        {
                            AddressID = 2u,
                            County = "Greater Manchester",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 2u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 53.501983299999999,
                            LineOne = "Queens Rd",
                            LineTwo = "",
                            Longitude = -2.2276524000000002,
                            PostCode = "M8 0RB"
                        },
                        new
                        {
                            AddressID = 3u,
                            County = "Greater Manchester",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 3u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 53.501179299999997,
                            LineOne = "7 Firth Cl",
                            LineTwo = "Salford",
                            Longitude = -2.2608823,
                            PostCode = "M7 2YD"
                        },
                        new
                        {
                            AddressID = 4u,
                            County = "Greater Manchester",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 4u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 53.475851200000001,
                            LineOne = "16-17 Watson St",
                            LineTwo = "",
                            Longitude = -2.2485708999999998,
                            PostCode = "M3 4LP"
                        },
                        new
                        {
                            AddressID = 5u,
                            County = "Greater Manchester",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 5u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 53.474063200000003,
                            LineOne = "45 York St",
                            LineTwo = "",
                            Longitude = -2.2389632000000002,
                            PostCode = "M1 7DE"
                        },
                        new
                        {
                            AddressID = 6u,
                            County = "Greater Manchester",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 6u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 53.470544599999997,
                            LineOne = "21 Textile St",
                            LineTwo = "",
                            Longitude = -2.1930223999999998,
                            PostCode = "M12 5DJ"
                        },
                        new
                        {
                            AddressID = 7u,
                            County = "Greater Manchester",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 7u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 53.446658999999997,
                            LineOne = "334-336 Platt Ln",
                            LineTwo = "",
                            Longitude = -2.2387429999999999,
                            PostCode = "M14 7DA"
                        },
                        new
                        {
                            AddressID = 8u,
                            County = "Greater Manchester",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 8u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 53.476317299999998,
                            LineOne = "70 Edge Ln",
                            LineTwo = "Droylsden",
                            Longitude = -2.1619087000000001,
                            PostCode = "M43 6BA"
                        },
                        new
                        {
                            AddressID = 9u,
                            County = "Greater Manchester",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 9u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 53.485469700000003,
                            LineOne = "3 Blackfriars Rd",
                            LineTwo = "Salford",
                            Longitude = -2.2507649999999999,
                            PostCode = "M3 7AQ"
                        },
                        new
                        {
                            AddressID = 10u,
                            County = "Greater Manchester",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 10u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 53.493595499999998,
                            LineOne = "3 Collingham St",
                            LineTwo = "",
                            Longitude = -2.2351911000000002,
                            PostCode = "M8 8RQ"
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Garage", b =>
                {
                    b.Property<uint>("GarageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<double>("BasePrice")
                        .HasColumnType("double(5, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("GarageName")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentEmail")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<uint>("UserID")
                        .HasColumnType("int unsigned");

                    b.HasKey("GarageID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Garages");

                    b.HasData(
                        new
                        {
                            GarageID = 1u,
                            BasePrice = 80.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manchester's Leading Accident Repair Centre. Sapphire Garage was founded 25 years ago in one small unit on a trading estate in East Manchester.",
                            GarageName = "Sapphire Garage",
                            ImagePath = "http://www.sapphiregarage.co.uk/wp-content/uploads/2017/05/sapphire_garage_logo.png",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentEmail = "payment@sapphiregarage.co.uk",
                            UserID = 1u
                        },
                        new
                        {
                            GarageID = 2u,
                            BasePrice = 50.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Local garage run by two mechanics",
                            GarageName = "Queens Garage",
                            ImagePath = "http://placehold.it/32x32",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentEmail = "admin@queensgarage.com",
                            UserID = 2u
                        },
                        new
                        {
                            GarageID = 3u,
                            BasePrice = 60.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Alternator and Starter Motor specialists. Servicing vehicles in Salford and Greater Manchester for over 35 years.",
                            GarageName = "EMS GARAGE",
                            ImagePath = "http://placehold.it/32x32",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentEmail = "payment@emsgarage.co.uk",
                            UserID = 3u
                        },
                        new
                        {
                            GarageID = 4u,
                            BasePrice = 68.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "One of the largest independent Service Centres and MOT Stations in Manchester City Centre.",
                            GarageName = "Duffy Motors",
                            ImagePath = "https://duffymotors.co.uk/wp-content/themes/duffy/library/img/logo.png",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentEmail = "payment@duffymotors.co.uk",
                            UserID = 4u
                        },
                        new
                        {
                            GarageID = 5u,
                            BasePrice = 90.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DC Motor Engineers Garage is a premium MOT Testing Centre, car servicing and repair facility. Based in the centre of Manchester, 2 minutes walk from oxford road station and the University, our garage offers an unparalleled service.",
                            GarageName = "DC Motor Engineers",
                            ImagePath = "http://placehold.it/32x32",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentEmail = "payment@mot-test-manchester.co.uk",
                            UserID = 5u
                        },
                        new
                        {
                            GarageID = 6u,
                            BasePrice = 74.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Small team of dedicated mechanics with long track record of excellent service and recovery",
                            GarageName = "Birch Lane Garage",
                            ImagePath = "http://placehold.it/32x32",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentEmail = "charlie@birchlanegarage.com",
                            UserID = 6u
                        },
                        new
                        {
                            GarageID = 7u,
                            BasePrice = 87.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "We are one of the leading car repair garages serving customers in Manchester. All mechanic services are performed by highly qualified mechanics.",
                            GarageName = "Platt Lane Garage",
                            ImagePath = "http://placehold.it/32x32",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentEmail = "payment@plattlanegarage.co.uk",
                            UserID = 7u
                        },
                        new
                        {
                            GarageID = 8u,
                            BasePrice = 79.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Established since 1920, Bradford Garage Ltd has been owned by the Spence family since 1963.",
                            GarageName = "Bradford Garage",
                            ImagePath = "http://placehold.it/32x32",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentEmail = "payment@bradfordgarage.co.uk",
                            UserID = 8u
                        },
                        new
                        {
                            GarageID = 9u,
                            BasePrice = 40.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Local garage with excellent services",
                            GarageName = "A Everall Garage",
                            ImagePath = "http://placehold.it/32x32",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentEmail = "payment@aeverallgarage.com",
                            UserID = 9u
                        },
                        new
                        {
                            GarageID = 10u,
                            BasePrice = 55.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Best Auto services in town.",
                            GarageName = "Z Cars Auto Services",
                            ImagePath = "http://placehold.it/32x32",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentEmail = "payment@zcarsautoservices.com",
                            UserID = 10u
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Invoice", b =>
                {
                    b.Property<uint>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("GarageID")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("UserID")
                        .HasColumnType("int unsigned");

                    b.HasKey("InvoiceID");

                    b.HasIndex("GarageID");

                    b.HasIndex("UserID");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceID = 1u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 1u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 11u
                        },
                        new
                        {
                            InvoiceID = 2u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 2u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 12u
                        },
                        new
                        {
                            InvoiceID = 3u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 3u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 13u
                        },
                        new
                        {
                            InvoiceID = 4u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 4u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 14u
                        },
                        new
                        {
                            InvoiceID = 5u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 5u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 15u
                        },
                        new
                        {
                            InvoiceID = 6u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 6u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 16u
                        },
                        new
                        {
                            InvoiceID = 7u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 7u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 17u
                        },
                        new
                        {
                            InvoiceID = 8u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 8u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 18u
                        },
                        new
                        {
                            InvoiceID = 9u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 9u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 19u
                        },
                        new
                        {
                            InvoiceID = 10u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 10u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 20u
                        });
                });

            modelBuilder.Entity("BackEnd.Models.PhoneNumber", b =>
                {
                    b.Property<uint>("PhoneNumberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<uint>("UserID")
                        .HasColumnType("int unsigned");

                    b.HasKey("PhoneNumberID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("PhoneNumbers");

                    b.HasData(
                        new
                        {
                            PhoneNumberID = 1u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "0161 202 8600",
                            UserID = 1u
                        },
                        new
                        {
                            PhoneNumberID = 2u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "0161 203 4180",
                            UserID = 2u
                        },
                        new
                        {
                            PhoneNumberID = 3u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "0161 792 2824",
                            UserID = 3u
                        },
                        new
                        {
                            PhoneNumberID = 4u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "0161 834 4168",
                            UserID = 4u
                        },
                        new
                        {
                            PhoneNumberID = 5u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "0161 273 4244",
                            UserID = 5u
                        },
                        new
                        {
                            PhoneNumberID = 6u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "0161 224 6633",
                            UserID = 6u
                        },
                        new
                        {
                            PhoneNumberID = 7u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "0161 225 4224",
                            UserID = 7u
                        },
                        new
                        {
                            PhoneNumberID = 8u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "0161 370 5664",
                            UserID = 8u
                        },
                        new
                        {
                            PhoneNumberID = 9u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "0161 835 1699",
                            UserID = 9u
                        },
                        new
                        {
                            PhoneNumberID = 10u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "07973 341794",
                            UserID = 10u
                        },
                        new
                        {
                            PhoneNumberID = 11u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "205-807-0833",
                            UserID = 11u
                        },
                        new
                        {
                            PhoneNumberID = 12u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "703-467-0416",
                            UserID = 12u
                        },
                        new
                        {
                            PhoneNumberID = 13u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "703-720-4438",
                            UserID = 13u
                        },
                        new
                        {
                            PhoneNumberID = 14u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "313-962-1315",
                            UserID = 14u
                        },
                        new
                        {
                            PhoneNumberID = 15u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "210-659-1915",
                            UserID = 15u
                        },
                        new
                        {
                            PhoneNumberID = 16u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "714-923-1921",
                            UserID = 16u
                        },
                        new
                        {
                            PhoneNumberID = 17u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "937-443-8221",
                            UserID = 17u
                        },
                        new
                        {
                            PhoneNumberID = 18u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "606-289-0588",
                            UserID = 18u
                        },
                        new
                        {
                            PhoneNumberID = 19u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "509-728-9569",
                            UserID = 19u
                        },
                        new
                        {
                            PhoneNumberID = 20u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "801-936-6137",
                            UserID = 20u
                        },
                        new
                        {
                            PhoneNumberID = 21u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "903-882-6027",
                            UserID = 21u
                        },
                        new
                        {
                            PhoneNumberID = 22u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "352-419-8539",
                            UserID = 22u
                        },
                        new
                        {
                            PhoneNumberID = 23u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = " 903-440-3569",
                            UserID = 23u
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Review", b =>
                {
                    b.Property<uint>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Body")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("GarageID")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Rating")
                        .HasColumnType("double(2, 1)");

                    b.Property<uint>("UserID")
                        .HasColumnType("int unsigned");

                    b.HasKey("ReviewID");

                    b.HasIndex("GarageID");

                    b.HasIndex("UserID");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewID = 1u,
                            Body = "Very fast serivce and got on the road quickly",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 1u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5.0,
                            UserID = 11u
                        },
                        new
                        {
                            ReviewID = 2u,
                            Body = "Fixed on site quickly",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 1u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5.0,
                            UserID = 14u
                        },
                        new
                        {
                            ReviewID = 3u,
                            Body = "Said would take an hour but ended up three, took too long",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 1u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2.0,
                            UserID = 16u
                        },
                        new
                        {
                            ReviewID = 4u,
                            Body = "Slow arriving but fixed car quickly",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 2u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3.0,
                            UserID = 12u
                        },
                        new
                        {
                            ReviewID = 5u,
                            Body = "Great service and prices. Very good Staff",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 2u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.0,
                            UserID = 22u
                        },
                        new
                        {
                            ReviewID = 6u,
                            Body = "Far too long waiting for them",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 2u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2.0,
                            UserID = 19u
                        },
                        new
                        {
                            ReviewID = 7u,
                            Body = "Good service but pricey",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 3u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3.0,
                            UserID = 14u
                        },
                        new
                        {
                            ReviewID = 8u,
                            Body = "Excellent service, quick response",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 3u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5.0,
                            UserID = 17u
                        },
                        new
                        {
                            ReviewID = 9u,
                            Body = "Quick arrival and mechanic very nice",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 4u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.0,
                            UserID = 11u
                        },
                        new
                        {
                            ReviewID = 10u,
                            Body = "Said could fix car on site but had they had to tow it back to their garage",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 4u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 1.0,
                            UserID = 12u
                        },
                        new
                        {
                            ReviewID = 11u,
                            Body = "Speedy service and on road quickly",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 4u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5.0,
                            UserID = 13u
                        },
                        new
                        {
                            ReviewID = 12u,
                            Body = "Super fast service but quite dear",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 4u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.0,
                            UserID = 14u
                        },
                        new
                        {
                            ReviewID = 13u,
                            Body = "Great service",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 5u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.0,
                            UserID = 20u
                        },
                        new
                        {
                            ReviewID = 14u,
                            Body = "Arrived quickly but took long time fixing car",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 6u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2.0,
                            UserID = 14u
                        },
                        new
                        {
                            ReviewID = 15u,
                            Body = "Arrived ten minutes later than they said and took while to get car running",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 6u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3.0,
                            UserID = 15u
                        },
                        new
                        {
                            ReviewID = 16u,
                            Body = "Too slow and pricey, would not recommend",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 6u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 1.0,
                            UserID = 16u
                        },
                        new
                        {
                            ReviewID = 17u,
                            Body = "Top work on my van",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 7u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5.0,
                            UserID = 17u
                        },
                        new
                        {
                            ReviewID = 18u,
                            Body = "Super fast service and fixed within minutes",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 7u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5.0,
                            UserID = 18u
                        },
                        new
                        {
                            ReviewID = 19u,
                            Body = "Friendly & helpful service with quick resolution.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 7u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.0,
                            UserID = 19u
                        },
                        new
                        {
                            ReviewID = 20u,
                            Body = "Overpriced",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 8u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 1.0,
                            UserID = 20u
                        },
                        new
                        {
                            ReviewID = 21u,
                            Body = "Lovely friendly guys! Fast and efficient service. Thanks very much.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 8u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5.0,
                            UserID = 21u
                        },
                        new
                        {
                            ReviewID = 22u,
                            Body = "Proper family honest garage service, quick response and friendly.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 8u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.0,
                            UserID = 22u
                        },
                        new
                        {
                            ReviewID = 23u,
                            Body = "Took too long, felt like wasted time",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 8u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2.0,
                            UserID = 23u
                        },
                        new
                        {
                            ReviewID = 24u,
                            Body = "Brilliant professional and friendly service, at very reasonable prices.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 9u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5.0,
                            UserID = 22u
                        },
                        new
                        {
                            ReviewID = 25u,
                            Body = "Competent mechanics. Don't try and do loads of unnecessary work. A good job at a good price",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 9u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.0,
                            UserID = 12u
                        },
                        new
                        {
                            ReviewID = 26u,
                            Body = "Acceptable service",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 9u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3.0,
                            UserID = 11u
                        },
                        new
                        {
                            ReviewID = 27u,
                            Body = "10/10 quality service.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 9u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5.0,
                            UserID = 15u
                        },
                        new
                        {
                            ReviewID = 28u,
                            Body = "A great service as always. A huge THANK YOU.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 9u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.0,
                            UserID = 18u
                        },
                        new
                        {
                            ReviewID = 29u,
                            Body = "Used this garage on several occasions, first class service. The Staff are always very pleasant and helpful.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 9u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.0,
                            UserID = 17u
                        },
                        new
                        {
                            ReviewID = 30u,
                            Body = "Took too long to arrive, said would be 30 minutes but it was hour and half, unacceptable",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 10u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 1.0,
                            UserID = 16u
                        },
                        new
                        {
                            ReviewID = 31u,
                            Body = "Good place for quick recovery",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 10u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.0,
                            UserID = 15u
                        },
                        new
                        {
                            ReviewID = 32u,
                            Body = "Very friendly staff, quick response",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 10u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5.0,
                            UserID = 19u
                        },
                        new
                        {
                            ReviewID = 33u,
                            Body = "Amazingly fast service, got on road again in no time",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageID = 10u,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5.0,
                            UserID = 20u
                        });
                });

            modelBuilder.Entity("BackEnd.Models.User", b =>
                {
                    b.Property<uint>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("PaymentEmail")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@sapphiregarage.co.uk",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sapphire Garage",
                            Password = "sapphire",
                            PaymentEmail = "payment@sapphiregarage.co.uk",
                            Username = "sapphiregarage"
                        },
                        new
                        {
                            UserID = 2u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@queensgarage.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Queens Garage",
                            Password = "queens",
                            PaymentEmail = "admin@queensgarage.com",
                            Username = "queensgarage"
                        },
                        new
                        {
                            UserID = 3u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hello@jemsgarage.co.uk",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "EMS GARAGE",
                            Password = "ems",
                            PaymentEmail = "ems@emsgarage.co.uk",
                            Username = "emsgarage"
                        },
                        new
                        {
                            UserID = 4u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "duffy@duffymotors.co.uk",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Duffy Motors",
                            Password = "duffy",
                            PaymentEmail = "admin@duffymotors.co.uk",
                            Username = "duffymotors"
                        },
                        new
                        {
                            UserID = 5u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hello@mot-test-manchester.co.uk",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "DC Motors",
                            Password = "dc",
                            PaymentEmail = "payment@mot-test-manchester.co.uk",
                            Username = "dcmotors"
                        },
                        new
                        {
                            UserID = 6u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "charlie@birchlanegarage.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Birch Lane Garage",
                            Password = "birch",
                            PaymentEmail = "payment@birchlanegarage.com",
                            Username = "birchlane"
                        },
                        new
                        {
                            UserID = 7u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@plattlanegarage.co.uk",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Platt Lange",
                            Password = "platt",
                            PaymentEmail = "payment@plattlanegarage.co.uk",
                            Username = "plattlane"
                        },
                        new
                        {
                            UserID = 8u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "brad@bradfordgarage.co.uk",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bradford Garage",
                            Password = "bradg",
                            PaymentEmail = "payment@bradfordgarage.co.uk",
                            Username = "bradfordgarage"
                        },
                        new
                        {
                            UserID = 9u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "everall@aeverallgarage.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "A Everall",
                            Password = "everall",
                            PaymentEmail = "payment@aeverallgarage.com",
                            Username = "aeverall"
                        },
                        new
                        {
                            UserID = 10u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hello@zcarsautoservices.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Z Cars Auto Services",
                            Password = "zcars",
                            PaymentEmail = "payment@zcarsautoservices.com",
                            Username = "Z Cars"
                        },
                        new
                        {
                            UserID = 11u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joy.heidenrei@gmail.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kurt K Koski",
                            Password = "joy",
                            PaymentEmail = "joy.heidenrei@gmail.com",
                            Username = "heidenrei"
                        },
                        new
                        {
                            UserID = 12u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "olaf.volkma6@gmail.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "William L Chester",
                            Password = "olaf",
                            PaymentEmail = "olaf.volkma6@gmail.com",
                            Username = "volkma"
                        },
                        new
                        {
                            UserID = 13u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sydney1983@yahoo.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kenneth C Surratt",
                            Password = "libra",
                            PaymentEmail = "sydney1983@yahoo.com",
                            Username = "surratt"
                        },
                        new
                        {
                            UserID = 14u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kareem2017@yahoo.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jacqulyn J Mooney",
                            Password = "never",
                            PaymentEmail = "kareem2017@yahoo.com",
                            Username = "mooney"
                        },
                        new
                        {
                            UserID = 15u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jordy2015@gmail.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Joy J Witt",
                            Password = "witty",
                            PaymentEmail = "jordy2015@gmail.com",
                            Username = "joyj"
                        },
                        new
                        {
                            UserID = 16u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fidel_oko5@hotmail.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Clifford D Phillips",
                            Password = "angie",
                            PaymentEmail = "fidel_oko5@hotmail.com",
                            Username = "fideloko"
                        },
                        new
                        {
                            UserID = 17u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "destiny1972@gmail.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Joyce B Ray",
                            Password = "apric",
                            PaymentEmail = "destiny1972@gmail.com",
                            Username = "bray"
                        },
                        new
                        {
                            UserID = 18u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "macy1983@yahoo.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Geneva S Gonzalez",
                            Password = "maystreet",
                            PaymentEmail = "macy1983@yahoo.com",
                            Username = "gonzalez"
                        },
                        new
                        {
                            UserID = 19u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "keanu_ernse1@yahoo.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Donna R Hayes",
                            Password = "sunvalley",
                            PaymentEmail = "keanu_ernse1@yahoo.com",
                            Username = "hayes"
                        },
                        new
                        {
                            UserID = 20u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maggie2004@hotmail.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "James N Jordan",
                            Password = "jnj",
                            PaymentEmail = "maggie2004@hotmail.com",
                            Username = "jordy"
                        },
                        new
                        {
                            UserID = 21u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ro.gorczan1@hotmail.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mercedes E Armstrong",
                            Password = "emerc",
                            PaymentEmail = "ro.gorczan1@hotmail.com",
                            Username = "armstrong"
                        },
                        new
                        {
                            UserID = 22u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "reyes2004@yahoo.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Refugio L Porter",
                            Password = "lport",
                            PaymentEmail = "reyes2004@yahoo.com",
                            Username = "refugio"
                        },
                        new
                        {
                            UserID = 23u,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "damion_powlows@hotmail.com",
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cindy A Butts",
                            Password = "powlows",
                            PaymentEmail = "damion_powlows@hotmail.com",
                            Username = "cindya"
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Address", b =>
                {
                    b.HasOne("BackEnd.Models.Garage", "Garage")
                        .WithOne("Address")
                        .HasForeignKey("BackEnd.Models.Address", "GarageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.Garage", b =>
                {
                    b.HasOne("BackEnd.Models.User", "User")
                        .WithOne("Garage")
                        .HasForeignKey("BackEnd.Models.Garage", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.Invoice", b =>
                {
                    b.HasOne("BackEnd.Models.Garage", "Garage")
                        .WithMany("Invoice")
                        .HasForeignKey("GarageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.User", "User")
                        .WithMany("Invoice")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.PhoneNumber", b =>
                {
                    b.HasOne("BackEnd.Models.User", "User")
                        .WithOne("PhoneNumber")
                        .HasForeignKey("BackEnd.Models.PhoneNumber", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.Review", b =>
                {
                    b.HasOne("BackEnd.Models.Garage", "Garage")
                        .WithMany("Review")
                        .HasForeignKey("GarageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.User", "User")
                        .WithMany("Review")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
